### ISSUE TITLE
OA&OP/Trauma: Navigation path at top of page

### ISSUE THREAD

**Issue by cuboideum** [AnthroGraph/PBP-App#19]
In the OA & OP dataset section template it says in [line 2](https://github.com/AnthroGraph/PBP-App/blob/575466322b02fc8bde31e8b988db4af7c37d7e56/data/templates/Template%253Ahttp%253A%252F%252Fw3id.org%252Frdfbones%252Fext%252Fphaleron-patho%252FOsteoarthritisAndOsteoporosisDatasetSection.html#L2):

> <h4>You are currently viewing/editing Bone Addition Section: <strong>[[this.label]]</strong></h4>

Here, "Bone Addition" needs to be replaced with "Osteoarthritis and Osteoporosis".

**Comment by zarquon42b** [comment]
Trauma had the same issue that has been addressed in https://github.com/AnthroGraph/PBP-App/pull/20
