### ISSUE TITLE
OA&OP: ROI selection

### ISSUE THREAD

**Issue by cuboideum** [AnthroGraph/PBP-App#21]
In the [PBP_Patho_AddPathologySectionNoROISpec template](https://github.com/AnthroGraph/PBP-App/blob/master/data/templates/http%253A%252F%252Fwww.metaphacts.com%252Fresource%252FPBP_Patho_AddPathologySectionNoROISpec_Template.html#L76), the options for selection of a ROI is based on subclasses of class phaleron-app:AnatomicalROIGroup. This is specified in [line 76](https://github.com/AnthroGraph/PBP-App/blob/215d4238ef52211e03f32eac6388c6f08f990280/data/templates/http%253A%252F%252Fwww.metaphacts.com%252Fresource%252FPBP_Patho_AddPathologySectionNoROISpec_Template.html#L76):

> ?ROIclass rdfs:subClassOf <http://w3id.org/rdfbones/anthrograph/app/phaleron-app/AnatomicalROIGroup> .

Instead, it should be based on subclasses of class phaleron-app:ArticularROIGroup.

The URI was incorrectly specified in the construction plan (cf. https://github.com/RDFBones/RDFBonesGraphics/issues/3).

**Comment by zarquon42b** [comment]
Can we please make the ROIs subclass of AnatomicalROIGroup? Otherwise, the code is not universal any more.

**Comment by zarquon42b** [comment]
Ah, OK, I now understand. It is only about the NOROISpec template. I now added this class as an additional option, so we don't have to change the classes (not yet commited). But there are the instances missing: analogous to` <http://w3id.org/rdfbones/anthrograph/app/phaleron-app/PhaleronSkullROIs>` I would expect a `<http://w3id.org/rdfbones/anthrograph/app/phaleron-app/PhaleronSkullArticularROIs>`
EDIT: also needed for the urlparam to redirect to the correct tab.
