### ISSUE TITLE
Bone add/loss no options available under ROI specification

### ISSUE THREAD

**Issue by cuboideum** [AnthroGraph/PBP-App#26]
@hayesleigh in issue https://github.com/RDFBones/RDFBonesPhaleron/issues/50:

>**In what module does the bug occur?**
>
>Within the bone addition and the bone loss sections in the paleopathology module, certain regions do not have options listed under the ROI specification.
>
>We encountered this error specifically in the thorax and shoulder girdle sections. Tried refreshing the page and this did not resolve the issue.
>
>![ROI specification no option](https://user-images.githubusercontent.com/90316213/156236145-ad0a7cad-821b-4b89-92a3-5d25dd804c3d.png)

Please close https://github.com/RDFBones/RDFBonesPhaleron/issues/50 with this one.

**Comment by 15E601** [comment]
Certain ROIs simply do not appear in the list, and this issue exists across many tabs. This includes for example in the **vertebral column** tab the left and right **lateral masses of the sacrum** (body of sacrum can be found), as well as in the **os coxae** tab the left and right **auricular regions**

**Comment by zarquon42b** [comment]
Cannot reproduce this error. BTW: it only lists ROIs that are scored "observable". Also check the ontology if all ROIs are correctly attached to the respective PhaleronROI

**Comment by zarquon42b** [comment]
This is the same as #24
