### ISSUE TITLE
Implement 'Vertebral Pathologies' module

### ISSUE THREAD

**Issue by cuboideum** [AnthroGraph/PBP-App#34]
With commit https://github.com/RDFBones/Phaleron-Pathologies/commit/64a6cba9529cb98e25cdd7eb58b47a1318284ca1 the RDFBones ontology extension phaleron-patho is updated to the extent that implementation of the 'Vertebral Pathologies' module in AnthroGraph is possible.

Further resources:

  *  [Mockups](https://github.com/RDFBones/RDFBonesGraphics/blob/main/Mockups/OntologyExtensions/phaleron-patho/phaleron-patho_VertebralPathologies_Mockups)
  *  [Building plan](https://github.com/RDFBones/RDFBonesGraphics/blob/main/NetworkGraphics/OntologyExtensions/phaleron-patho/phaleron-patho_VertebralPathologies_NetworkGraphics.svg)

Note that the 'Ankylosis' relationship relates the region of interest that the dataset section is about AND one or two other regions of interest. The [network graphics file](https://github.com/RDFBones/RDFBonesGraphics/blob/main/NetworkGraphics/OntologyExtensions/phaleron-patho/phaleron-patho_VertebralPathologies_NetworkGraphics.svg) contains a drawing illustrating the ankylosis relation by example.

**Comment by zarquon42b** [comment]
Done in #35
