### ISSUE TITLE
General tab for paleopathology module

### ISSUE THREAD

**Issue by cuboideum** [AnthroGraph/PBP-App#38]
The paleopathology module requires a tab 'General', similar to the one in skeletal inventories. This is essential as datasets without any observations state that a skeleton does not yield paleopathological evidence. It is necessary to record who found this out. Such cases are also likely to inspire comments.

Minimum set of elements:

* comments box
* research contribution processes

**Comment by zarquon42b** [comment]
What would be the appropriate Observation/Process to attach the RP to? If so, this item needs to be created upon dataset creation.
Would this be the Investigation of class PaleopathologyInvestigation itself? I have already added this locally and can push it if you deem it sensible.

**Comment by cuboideum** [comment]
Yes, the process which is annotated by the comment box and of which the research contribution processes are subprocesses of is phaleron-patho:PaleopathologicalInvestigation.
