### ISSUE TITLE
Skeletal Inventory: Improve structure of 'Vertebral Column' tab

### ISSUE THREAD

**Issue by cuboideum** [AnthroGraph/PBP-App#6]
In the skeletal inventory module, the tab containing data item about the vertebral column is structured as follows:

* Left Parts of Vertebral Column
* Sacrum
* Right lateral Mass of Sacrum
* Bodies of vertebral Column
* Sacrum
* Grouped Elements
* Cervical Vertebrae, grouped
* Thoracic Vertebrae, grouped
* Lumbar Vertebrae, grouped
* Unsided Fragments of Sacrum
* Number of coccygeal Units
* Taphonomy of the entire vertebral Column

Navigation through the form is cumbersome because it is a long list of elements. This could be improved by solving the following problems:

* The structure is inconsistent (e.g. there is no 'Right Parts of Vertebral Column' section)
* The structure only has one level although some points are clearly subcategories of others (e.g. multiple occurrence of 'Sacrum')
* Capitalisation is inconsistent (e.g. sometimes it is 'Vertebral Column', sometimes 'vertebral Column) and should follow some general rule.

I suggest restructuring according to the following scheme:

* Left Parts of Vertebral Column
     * Cervical vertebrae
     * Thoracic vertebrae
     * Lumbar vertebrae
     * Sacrum
* Right Parts of Vertebral Column
     * Cervical vertebrae
     * Thoracic vertebrae
     * Lumbar vertebrae
     * Sacrum
* Central Parts of Vertebral Column
     * Cervical vertebrae
     * Thoracic vertebrae
     * Lumbar vertebrae
     * Sacrum
* Grouped Elements
     * Cervical vertebrae, grouped
     * Thoracic vertebrae, grouped
     * Lumbar vertebrae, grouped
     * Unsided fragments of sacrum
     * Number of coccygeal units
* Taphonomy of Entire Vertebral Column

**Comment by 15E601** [comment]
Fixed in #10
