### ISSUE TITLE
Wrong cardinality in long bone size and shape section

### ISSUE THREAD

**Issue by 15E601** [AnthroGraph/PBP-App#68]
The cardinality for the degree MDs that result from the switch events in the size and shape sections is "10" instead of "1", meaning the two mutually exclusive values possible can be added to the same MD.

![image](https://github.com/AnthroGraph/PBP-App/assets/67172847/9dfad2ed-64c6-4802-8659-aac9ab3dc913)

**Comment by zarquon42b** [comment]
Closed with merge
