### ISSUE TITLE
Incorrect class used for standards-patho/ActivityOfPathologicalProcess

### ISSUE THREAD

**Issue by 15E601** [AnthroGraph/PBP-App#72]
The osteopaleopath module saves measurement data of the type 'Activity of pathological process' under the IRI
`phaleron-patho/ActivityOfPathologicalProcess`. This class does not exist in the ontology, where it is instead
`standards-patho/ActivityOfPathologicalProcess`

In the template http://w3id.org/rdfbones/ext/phaleron-patho/BoneLossDatasetSection
The line `connected_class="phaleron-patho:ActivityOfPathologicalProcess"`
must be replaced with `connected_class="standards-patho:ActivityOfPathologicalProcess"`

Furthermore, all classes already saved with the incorrect class must have their rdf:type triple replaced with the correct class

(This is a follow-up on issue RDFBones/RDFBones-O#192)

**Comment by zarquon42b** [comment]
Fixed and triples updated in production platform
